2023WinterBootCamp-Team-L/CloverFeed

- backend/Dockerfile
> chore/#9 백엔드 dockerfile 수정

- frontend/Dockerfile
- frontend/vite.config.ts
> chore: 프론트엔드 dockerfile 수정

- frontend/src/pages/QueryMain.tsx
QueryMain 충돌 수정
> #23
QueryMain 충돌 수정
> feat: QueryMain 수정

- backend/cloverfeed/admin.py
- backend/cloverfeed/apps.py
- backend/cloverfeed/models.py
- backend/cloverfeed/tests.py
- backend/cloverfeed/views.py
> chore: django 프로젝트 생성

- frontend/src/components/Toggle.tsx
- frontend/src/pages/QueryList.tsx
- frontend/src/pages/QueryShare.tsx
- frontend/src/pages/QueryStart.tsx
질문폼 모달창 구현 완료
> #41
질문폼 모달창 구현 완료
> feat: 질문폼 모달창 구현 완료

- frontend/package.json
- frontend/src/App.tsx
- frontend/src/components/Line.tsx
- frontend/src/pages/Chart.tsx
- frontend/yarn.lock
> feat: Chart 퍼블리싱

- frontend/src/components/GreenButton.tsx
GreenButton 수정
> #23 
GreenButton width 수정
> fix: GreenButton 수정

- frontend/src/components/FeedbackBox.tsx
- frontend/src/components/Searchbutton.tsx
- frontend/src/components/wordcloud.tsx
- frontend/src/pages/Mainpage.tsx
- frontend/src/pages/Search.tsx
검색 기능 구현 및 검색 페이지 디자인 수정
> #75 
검색 기능 구현 및 검색 페이지 디자인 수정
> feat: 검색 기능 구현 및 디자인 수정

- backend/cloverfeed/serializers.py
- backend/cloverfeed/urls.py
- backend/cloverfeed/views.py
사용자가 받은 피드백답변들 중 주관식 내용으로만 제한하여 검색
> #91 
검색어 있는경우 vs 검색어 없는경우(모든 답변 보여줌)
> feat:받은 피드백답변(주관식) 내용 검색

- backend/cloverfeed/views.py
> fix: 카테고리(직군) 추가

- backend/cloverfeed/serializers.py
- backend/cloverfeed/views.py
> fix: 질문 목록 확인 시 폼 없을 때 예외처리

- docker-compose.yml
> chore: MySQL Health Check

- backend/cloverfeed/serializers.py
> fix: serializer conflict 수정

- backend/cloverfeed/urls.py
- backend/cloverfeed/views.py
> fix: API 설계 수정 반영

- backend/config/settings.py
- backend/requirements.txt
- frontend/src/components/SuccessButton.tsx
- frontend/src/pages/Gosignup.tsx
> chore: django CORS 대응

- frontend/src/components/FeedCount.tsx
- frontend/src/pages/Chart.tsx
- frontend/src/pages/FeedBackList.tsx
> fix: api URI 수정

- frontend/my-react-app/package.json
- frontend/package.json
- frontend/src/App.tsx
- frontend/src/components/FeedButton.tsx
- frontend/src/components/FeedCount.tsx
- frontend/src/components/GologinButton.tsx
- frontend/src/pages/Chart.tsx
- frontend/src/pages/FeedBackList.tsx
- frontend/src/pages/FeedBackResult.tsx
- frontend/src/pages/Gosignup.tsx
> fix: 프록시 설정 해제

- frontend/src/App.tsx
- frontend/src/components/FeedButton.tsx
- frontend/src/components/FeedCount.tsx
- frontend/src/pages/Chart.tsx
- frontend/src/pages/FeedBackList.tsx
- frontend/src/pages/FeedBackResult.tsx
- frontend/src/pages/Mainpage.tsx
api url 수정
> #127 #85 #96 #130 
api url 수정(빠진 / 추가)
> fix: api url 수정

- backend/cloverfeed/authentication.py
- backend/cloverfeed/views.py
- backend/config/settings.py
> fix: 중복 회원가입 방지

- backend/cloverfeed/serializers.py
- backend/cloverfeed/views.py
> fix: 질문 목록 API 오류 해결

- frontend/src/components/FeedbackAnswerInput.tsx
- frontend/src/components/TagAnswer.tsx
- frontend/src/pages/Mainpage.tsx
디자인 세부사항 수정
> #133 
디자인 세부사항 수정
> design: 세부사항 수정

- backend/cloverfeed/views.py
> Fix/#185 API userid 파라미터 수정, 질문 내용 조회 시 최신 폼 내용만 받아오도록 수정

- frontend/atoms/AnswerStore.tsx
- frontend/atoms/QuestionStore.tsx
- frontend/src/components/Answer/ChoicePart.tsx
- frontend/src/components/FeedCount.tsx
- frontend/src/components/GologinButton.tsx
- frontend/src/components/ShareButton.tsx
- frontend/src/pages/Chart.tsx
- frontend/src/pages/FeedBackList.tsx
- frontend/src/pages/Gosignup.tsx
- frontend/src/pages/LinkAnswer.tsx
- frontend/src/pages/Mainpage.tsx
- frontend/src/pages/QueryList.tsx
- frontend/src/pages/Search.tsx
userid로컬스토리지
> #183
userid로컬스토리지
> Feat/#183 userid로컬스토리지

- frontend/src/components/Searchbutton.tsx
- frontend/src/pages/Search.tsx
검색 페이지 퍼블리싱 보완
> #133
검색 페이지 퍼블리싱 보완
> design: 검색 페이지 퍼블리싱 보완

- frontend/src/components/FeedButton.tsx
- frontend/src/components/FeedCount.tsx
- frontend/src/pages/FeedBackList.tsx
- frontend/src/pages/FeedBackResult.tsx
- frontend/src/pages/LinkAnswer.tsx
- frontend/src/pages/LinkFinish.tsx
- frontend/src/pages/Mainpage.tsx
전체 키워드 추출 및 요약 api 연동
> #191
전체 키워드 추출 및 요약 api 연동
> Feat/#191 전체키워드추출및요약api

- frontend/src/pages/Mainpage.tsx
Reverts 2023WinterBootCamp-Team-L/CloverFeed#215
> Revert "Design 주간발표"

- frontend/src/App.css
- frontend/src/components/GologinButton.tsx
- frontend/src/components/GreenButton.tsx
- frontend/src/components/LoginModal.tsx
- frontend/src/components/SuccessButton.tsx
- frontend/src/components/TagAnswer.tsx
- frontend/src/pages/Chart.tsx
- frontend/src/pages/FeedBackList.tsx
- frontend/src/pages/FeedBackResult.tsx
- frontend/src/pages/Gosignup.tsx
- frontend/src/pages/Login.tsx
- frontend/src/pages/Signup.tsx
Reverts 2023WinterBootCamp-Team-L/CloverFeed#214
> Revert "Design/#188 반응형 디자인"

- backend/cloverfeed/urls.py
- backend/cloverfeed/views.py
- frontend/src/App.tsx
- frontend/src/components/FeedbackBox.tsx
- frontend/src/pages/FeedBackList.tsx
- frontend/src/pages/FeedBackResult.tsx
- frontend/src/pages/Mainpage.tsx
- frontend/src/pages/Search.tsx
> Feat/#96 특정피드백상세내용확인api

- frontend/src/components/TagAnswer.tsx
- frontend/src/pages/FeedBackList.tsx
> fix: 태그 코드 수정

- frontend/src/App.css
- frontend/src/components/GologinButton.tsx
- frontend/src/components/GreenButton.tsx
- frontend/src/components/HomeButton.tsx
- frontend/src/components/SuccessButton.tsx
- frontend/src/pages/Chart.tsx
- frontend/src/pages/FeedBackList.tsx
- frontend/src/pages/FeedBackResult.tsx
- frontend/src/pages/Gosignup.tsx
- frontend/src/pages/LinkMain.tsx
- frontend/src/pages/LinkPosition.tsx
- frontend/src/pages/LinkStart.tsx
- frontend/src/pages/LinkTag1.tsx
- frontend/src/pages/LinkTag2.tsx
- frontend/src/pages/Login.tsx
- frontend/src/pages/Signup.tsx
페이지 반응형 디자인
> #218 
페이지 반응형 디자인
> Design/#218 페이지 반응형 디자인

- frontend/src/components/FeedbackBox.tsx
- frontend/src/components/Searchbutton.tsx
- frontend/src/components/Toggle.tsx
- frontend/src/pages/Mainpage.tsx
- frontend/src/pages/Search.tsx
검색페이지 태그 디자인
> #133
검색페이지 태그 디자인
> Design/#133 퍼블리싱보완

- frontend/src/components/GologinButton.tsx
- frontend/src/pages/Login.tsx
로그인페이지에 피드백폼 유무 조회 api 연동
> #67
로그인페이지에 피드백폼 유무 조회 api 연동
피드백 폼이 없을 경우 모달창 렌더링
> fix: 로그인페이지에 피드백폼 유무 조회 api 연동

- frontend/src/components/Answer/TagPart.tsx
> Feat/#165 피드백질문에답변제출api

- frontend/src/pages/Mainpage.tsx
> fix: 로그아웃 주소 수정

- frontend/src/pages/Search.tsx
검색페이지 중복 데이터 필터링
> #234
검색페이지 중복 데이터 필터링
> fix: 검색페이지 중복 데이터 필터링

- frontend/src/components/AnswerOptionList.tsx
- frontend/src/components/ShortButton.tsx
- frontend/src/pages/Chart.tsx
> fix: 빌드 오류들 수정

- backend/config/settings.py
> fix: OpenAI 키 삭제

- frontend/src/app/Query/add/page.tsx
- frontend/src/app/Query/page.tsx
- frontend/src/app/Query/start/page.tsx
- frontend/src/components/ChangePage.tsx
- frontend/src/components/GreenButton.tsx
- frontend/src/components/XButton.tsx
> refactor: 질문 작성 페이지 중 메인페이지 마이그레이션 완료
